### ISSUE TITLE
Using with Minecraft

### ISSUE THREAD

**Issue by josephisticated** [gyf304/lpvpn#27]
I was trying to create a Minecraft server to play with my friends, but using 192.168.42.2:(some port) in server section didn't work, is it something with CIDR? If not what do I do, i was just trying to create a LAN server.

**Comment by josephisticated** [comment]
half-life lan game works btw

**Comment by gyf304** [comment]
Hi. Thank you for your interest in LPVPN. However [Discord has deprecated their game SDK](https://discord.com/developers/docs/change-log#gamesdk-feature-deprecation), leaving this project in limbo. I've created another project [PartyLAN](https://github.com/gyf304/partylan) which is the same concept but using Steam instead. You can request a beta key there and start using PartyLAN instead. PartyLAN will eventually be released for free on Steam.
