### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by josephisticated** [gyf304/lpvpn#30]

**Comment by josephisticated** [comment]
> It works very well, here in Divinity Original Sin 2 we managed to connect without problems. ![eaeaeaqdqds](https://user-images.githubusercontent.com/22040744/245200807-85aa96a7-4075-4285-adad-c784e37fec04.PNG)

hmm, last time I tried discord wasn't generating invites, got to try.

**Comment by gyf304** [comment]
Hi. Thank you for your interest in LPVPN. However [Discord has deprecated their game SDK](https://discord.com/developers/docs/change-log#gamesdk-feature-deprecation), leaving this project in limbo. I've created another project [PartyLAN](https://github.com/gyf304/partylan) which is the same concept but using Steam instead. You can request a beta key there and start using PartyLAN instead. PartyLAN will eventually be released for free on Steam.
