### ISSUE TITLE
A small difficulty with CIDR IP in LPVPN

### ISSUE THREAD

**Issue by abctiwari** [gyf304/lpvpn#31]
Hi gyf304!

Firstly thanks for making this wonderful app. Thanks to it I can play a modern classic game Conflict Global Storm which was once upon a time only playable in co-op mode with now-defunct GameSpy. I play this with my younger brother.

A couple of months back, LPVPN started crashing all of a sudden in my brother's PC and he wasn't able to join. I could not figure out the root cause back then. But then today I attempted to give it another shot with him. Re-installed Discord in his PC and many other things. Finally, I was tires and casually as a random experiment, I tried to change the CIDR IP in my PC. Aloha! I saw the same issue replicated on my PC. I now remember that I asked him to change the CIDR IP for some silly reason and after that, this problem started in his PC, and then on my PC from today onwards.

The problem appears to be with the CIDR IP that is set to 192.168.42.1/24 by default. As per my observation, an attempt to change the same shall trigger the issue. After this, I tried to Host a game. The sent bytes now stay 0 at all times, and the Invite button no longer works (the join slots dialog is not initiated in Discord). (Screenshot attached).

Although restarting the LPVPN app resets all the IP settings, the Invite button no longer works, and the sent bytes are stuck to 0. The LPVPN adapter is also not created in Control Panel Network Connections. The problem still remains even if I use a different version of LPVPN exe file.

These are some of my observations. Also, I am a noob when it comes to coding, so I was just trying to use the compiled '.exe' files put the GitHub repository. I tried all the versions, but none of them worked. Any solutions are welcome from the other community members as well.

Appreciate the support! Thanks and sorry for the trouble.

Kind Regards,
Max!
![lpvpn_issue1](https://user-images.githubusercontent.com/131395850/233456598-e7a5008d-cdb7-4848-a304-933c88bd4fea.PNG)

**Comment by gyf304** [comment]
Hi. Thank you for your interest in LPVPN. However [Discord has deprecated their game SDK](https://discord.com/developers/docs/change-log#gamesdk-feature-deprecation), leaving this project in limbo. I've created another project [PartyLAN](https://github.com/gyf304/partylan) which is the same concept but using Steam instead. You can request a beta key there and start using PartyLAN instead. PartyLAN will eventually be released for free on Steam.
