### ISSUE TITLE
Recommended games to add

### ISSUE THREAD

**Issue by snds** [gyf304/lpvpn#4]
I love the idea of this application. I think it would be great if you'd look at this list to add more games: http://langamelist.com/

However, I do have some specific asks:
- Factorio
- Fistful of Frags
- Team Fortress 2
- Unreal Tournament 1999
- Unreal Tournament 2004
- Quake 3 Arena
- Command & Conquer Red Alert (Remaster or Open RA)
- Command & Conquer Red Alert 2
- Total Annihilation
- Supreme Commander: Forged Alliance
- Warcraft 2: Tides of Darkness
- Borderlands
- Borderlands 2
- Call of Duty
- Call of Duty 2
- Call of Duty 4: Modern Warfare
- Call of Duty: Modern Warfare 2
- Call of Duty: Modern Warfare 3
- Battlefield: Vietnam
- Battlefield: Bad Company 2
- Counter-Strike: Source
- Counter-Strike (1.6)
- Counter-Strike: Global Offensive

There are plenty more, but this list comes as a partial list from the link above. These are some older and newer games as well.

**Comment by gyf304** [comment]
For most games, LPVPN should already work. The list I provided only shows the games people (mostly me) have tested.
