### ISSUE TITLE
Add to documentation: Microsoft Visual C++ 2015-2019 Redistributable

### ISSUE THREAD

**Issue by mrwunderbar666** [gyf304/lpvpn#9]
Hi,
thanks for this awesome tool!

I just tried it and noticed that it requires the `vcruntime140_1.dll` which is included in the VC Redistributable (Link: https://aka.ms/vs/16/release/vc_redist.x64.exe).

I think it would be useful to add that piece of information to the readme.md?

**Comment by gyf304** [comment]
Thank you for reporting this. I'm going to attempt to resolve this while keeping the binary self-contained. If that fails, I will add that to the README.md.
Stay tuned.

**Comment by gyf304** [comment]
Resolved in v1.0.2
